apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-dqx-price
  namespace: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-dqx-price
  template:
    metadata:
      labels:
        app: streamlit-dqx-price
    spec:
      containers:
      - name: streamlit-dqx-price
        image: tig0826/streamlit-dqx-price
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-dqx-price
  namespace: streamlit
spec:
  type: ClusterIP
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: streamlit-dqx-price
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-dqx-price
  namespace: streamlit
spec:
  ingressClassName: traefik
  rules:
  - host: streamlit-dqx-price.mynet
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamlit-dqx-price
            port:
              number: 8501

